version: '3'
services: 
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./fibonacci-server
    volumes:
      - /app/node_modules/
      - ./fibonacci-server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: fibonacci-client
    volumes:
      - /app/node_modules
      - ./fibonacci-client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: fibonacci-worker
    volumes:
      - /app/node_modules
      - ./fibonacci-worker:/app